
#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "MDIO_REG.h"
#include "MPORT.h"
#include "MPORT_CFG.h"

MPORT_enuPinConfigration_t MPORT_enuArrPinConfig[MPORT_NUM_OF_PORTS * MPORT_NUM_OF_PINS] = 
{
    MPORT_PORTA_PIN0_CONFIGRATION,
    MPORT_PORTA_PIN1_CONFIGRATION, 
    MPORT_PORTA_PIN2_CONFIGRATION, 
    MPORT_PORTA_PIN3_CONFIGRATION, 
    MPORT_PORTA_PIN4_CONFIGRATION, 
    MPORT_PORTA_PIN5_CONFIGRATION, 
    MPORT_PORTA_PIN6_CONFIGRATION, 
    MPORT_PORTA_PIN7_CONFIGRATION, 
    MPORT_PORTB_PIN0_CONFIGRATION, 
    MPORT_PORTB_PIN1_CONFIGRATION, 
    MPORT_PORTB_PIN2_CONFIGRATION, 
    MPORT_PORTB_PIN3_CONFIGRATION, 
    MPORT_PORTB_PIN4_CONFIGRATION, 
    MPORT_PORTB_PIN5_CONFIGRATION, 
    MPORT_PORTB_PIN6_CONFIGRATION, 
    MPORT_PORTB_PIN7_CONFIGRATION, 
    MPORT_PORTC_PIN0_CONFIGRATION, 
    MPORT_PORTC_PIN1_CONFIGRATION, 
    MPORT_PORTC_PIN2_CONFIGRATION, 
    MPORT_PORTC_PIN3_CONFIGRATION, 
    MPORT_PORTC_PIN4_CONFIGRATION, 
    MPORT_PORTC_PIN5_CONFIGRATION, 
    MPORT_PORTC_PIN6_CONFIGRATION, 
    MPORT_PORTC_PIN7_CONFIGRATION, 
    MPORT_PORTD_PIN0_CONFIGRATION, 
    MPORT_PORTD_PIN1_CONFIGRATION, 
    MPORT_PORTD_PIN2_CONFIGRATION, 
    MPORT_PORTD_PIN3_CONFIGRATION, 
    MPORT_PORTD_PIN4_CONFIGRATION, 
    MPORT_PORTD_PIN5_CONFIGRATION, 
    MPORT_PORTD_PIN6_CONFIGRATION, 
    MPORT_PORTD_PIN7_CONFIGRATION
};